<!--
 * @Author: wxm-web 2402715813@qq.com
 * @Date: 2022-02-10 14:45:03
 * @LastEditors: wxm-web 2402715813@qq.com
 * @LastEditTime: 2022-05-22 19:52:49
 * @FilePath: \pathways\vignettes\Evaluation-Algorithm.Rmd
-->
---
title: "Evaluation-Algorithm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Evaluation-Algorithm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",out.height = "50%",
  message = F,warning = F,tidy = T
)
```

# pathways

<!-- badges: start -->
<!-- badges: end -->

The goal of pathways is to ...

## Installation

You can install the development version of pathways like so:

``` r
# FILL THIS IN! HOW CAN PEOPLE INSTALL YOUR DEV PACKAGE?
```

## Example

This is a basic example which shows you how to solve a common problem:


```{r cars}
library(pathways)
library(dplyr)
library(DOSE)
library(pathways)
library(tidyverse)
library(igraph)
library(ggraph)
load(system.file("data", "Tes.Rdata",package = "pathways"))
 n@kegg_analyst$compareClusterResult@compareClusterResult%>%dplyr::filter(org=="KEGG")%>%
 dplyr::filter(
(Description%in%c((n@kegg_analyst$compareClusterResult@compareClusterResult%>%group_by(Description)%>%
                    summarise(n=n()>1))%>%
                    dplyr::filter(n==T)%>%.$Description)|qvalue     <0.05)
)%>%as.data.frame()->f
circos.clear()
circos.par(cell.padding = c(0, 0, 0, 0), points.overflow.warning = FALSE,start.degree=90)
plot_chor(f,metaProfiler = n)->v
pd = packLegend(list =  v)
draw(pd, x = unit(1, "cm"), y = unit(1, "cm"), just = c("left", "bottom"))

```

```{r ds}
comp_dotplot(n@kegg_analyst$enrichKEGG$a)
n@kegg_analyst$enrichKEGG$a->lllll
lllll->da
da@result%>% dplyr::filter(org=="KEGG") ->y
#plot_funmap(y)
```